apiVersion: apps/v1
kind: Deployment
metadata:
  name: soap-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soap-service
  template:
    metadata:
      labels:
        app: soap-service
    spec:
      containers:
      - name: soap-service
        image: "brudnevskij/soap-service:1.0.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: soap-service
spec:
  selector:
    app: soap-service
  ports:
    - protocol: TCP
      name: main-port
      port: 8080
      targetPort: 8080